GET http://localhost:8080/ 

###

POST http://localhost:8080/auth/login 
Content-Type: application/json

{
    "email" : "faislabdu277@gmail.com",
    "password" : "123"
}

###
GET http://localhost:8080/data/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJlbWFpbCI6ImZhaXNsYWJkdTI3N0BnbWFpbC5jb20ifSwiaWF0IjoxNzI5OTE4NjU4LCJleHAiOjE3Mjk5MjIyNTh9.UtiI94ho3tING-L0kGN9TNsgr6g4-mNhSTuITBVK0F8


###   
PUT http://localhost:8080/data/modify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJlbWFpbCI6ImZhaXNsYWJkdTI3N0BnbWFpbC5jb20ifSwiaWF0IjoxNzI5OTE5MDA5LCJleHAiOjE3Mjk5MjI2MDl9.Wtx_W3dabSfOh5EN85WLY0EjORm3ptRp-ggDFejRQ4Y
Content-Type: application/json

{
    "email": "faislabdu277@gmail.com",
    "user_name": "Faisal999123",
    "fname": "Faisal H ",
    "lname": "Abdo"
}

###

POST http://localhost:8080/auth/request-password-reset 
Content-Type: application/json

{
  "email": "faislabdu277@gmail.com"
}
